### ISSUE TITLE
BUG: clicking on next candidate crashes VST3

### ISSUE THREAD

**Issue by AtmanActive** [StrangeLoopsAudio/gRainbow#60] opened 2023-06-07 13:50 UTC
Hi,

First of all, please let me congratulate you on developing this awesome software.
This is absolutely fantastic.
I'm blown away by what this synth does.
Incredible!

Now, when I was testing the x64 windows VST3 version in Reaper, everything was working flawlessly but I did manage to discover a bug / unhandled exception. When editing a pad, by clicking on the little asterisk above it and clicking on layer <> arrows that were displaying 1/6, the plug-in crashed, taking the Reaper down with it. I presume that this is due to the fact that I didn't have additional layers enabled on this pad, so the plug-in tried to switch to the next layer which wasn't there.

Just wanted to let you know.
Anyway, now I know to avoid those buttons.

Thank you for this VST gem.

**Comment by bboettcher3** [comment] 2023-06-07 14:14
Thanks for the report! I've gotten this from another user as well, so I'll try and track down the reason soon. By the way, the left/right arrows will change the position candidate (see [the terminology section on its page](https://bboettcher3.github.io/grainbow)), not the generator selected, you can instead click on the generator itself to change its parameters

**Comment by AtmanActive** [comment] 2023-06-07 15:07
Yeah, I was wondering how to alt/random the candidates.

Just thinking out loud here, maybe it would be useful to have global <> buttons/selectors to be able to switch the candidates on the fly, while performing (shifting maybe?).

In any case, thank you for this awesome software and keep up the good work!

**Comment by bboettcher3** [comment] 2023-06-09 20:33
@AtmanActive could you send me the audio file/preset that would produce this crash?

**Comment by AtmanActive** [comment] 2023-06-12 13:17
[Coka Vox GRainbow Synth - Promene Refren.zip](https://github.com/bboettcher3/gRainbow/files/11723534/Coka.Vox.GRainbow.Synth.-.Promene.Refren.zip)

Here it is.

**Comment by AtmanActive** [comment] 2023-06-12 13:27
![gRainbow_crash](https://github.com/bboettcher3/gRainbow/assets/7526717/4161715e-4128-477f-b0ce-fec627c4991b)

**Comment by bboettcher3** [comment] 2023-06-12 16:40
@AtmanActive I can't seem to reproduce this even with your file using reaper, could you try the most recent build to see if it's still happening for you? Hoping it might have been fixed with some other changes. https://github.com/bboettcher3/gRainbow/actions/runs/5239813157

**Comment by AtmanActive** [comment] 2023-06-12 20:00
Same behavior even with the latest build you referenced above.

Let me know if I can help you debug in any way.

**Comment by AtmanActive** [comment] 2023-06-12 20:06
I just did a test with a brand new, fresh portable installation of the latest Reaper version for windows x64 and the behavior is the same.

**Comment by AtmanActive** [comment] 2023-06-12 20:11
Crashing on my desktop machine where Reaper is running at 48kHz, but also crashing on my studio machine where Reaper is running at 192kHz.

**Comment by bboettcher3** [comment] 2023-06-13 18:37
Hmm, definitely something weird happening. I can only reproduce it when running the Release build, not in Debug.. which makes me think it's running into some sort of race condition somewhere. I'll try some things out...

**Comment by AtmanActive** [comment] 2023-06-27 10:41
Can confirm: these problems are now gone in v0.4.0.
Great work!
Thank you very much for this brilliant synth/sampler.

**Comment by bboettcher3** [comment] 2023-06-27 18:26
Great! I'll close this, feel free to re-open it if it comes back at all.

**Closed by bboettcher3** 2023-06-27 18:26 UTC
Labels: bug
